# Use a imagem oficial do Node.js baseada no Alpine
FROM node:14-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/server

# Copie o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código da aplicação para o diretório de trabalho
COPY . .

# Exponha a porta que a aplicação irá rodar
EXPOSE 3001

# Comando para rodar a aplicação
CMD ["npm", "start"]