name: Github Actions Build
on:
  push:
   branches:
     - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: Deploy project with ssh
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.IPADRESS }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.BOB }}
            script: |
                cd ./srv/LearningCloudNativeExercise
                git pull origin main