name: GitHub Actions Build
run-name: ${{ github.actor }} running for integration
on: 
  push:
    branches:
        - main
jobs:
   Automerge-into-main:
    runs-on: ubuntu-latest
    steps:
        - run: git checkout main
        - run: git merge develop
        - run: echo "On a mergé"